# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Map4D' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Map4D
  pod 'Map4dMap'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'R.swift'
  pod 'RxAlamofire'
  pod 'RxDataSources'
  pod 'RxUIAlert'

  target 'Map4DTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Map4DUITests' do
    # Pods for testing
  end
  
  target 'Model' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelTests' do
    # Pods for testing
  end
  
  target 'ViewModel' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViewModelTests' do
    # Pods for testing
  end

end
